name: Coverage Upload Action
description: Upload code coverage to a remote endpoint
author: Neo Financial Engineering
branding:
  icon: upload-cloud
  color: blue
inputs:
  coverageData:
    description: 'location of lcov coverage file (default: coverage/lcov.info)'
    default: 'coverage/lcov.info'
    required: false
  coverageEndpoint:
    description: endpoint to send coverage to
    required: false
  coverageToken:
    description: token to send with coverage data
    required: false
  customMessage:
    description: toggle if the coverageEndpoint expects to respond with the custom message or just the difference
    default: 'comment'
    required: false
runs:
  using: 'node16'
  main: 'build/index.js'
